services:
  kafbat-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafbat-ui
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: kraft-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:19092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
      # KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-256
      # KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret";'
      KAFKA_CLUSTERS_0_SSL_TRUSTSTORELOCATION: /etc/kafka/secrets/truststore.jks
      KAFKA_CLUSTERS_0_SSL_TRUSTSTOREPASSWORD: changeit
      KAFKA_CLUSTERS_0_SSL_VERIFYSSL: true
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/client.keystore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEY_PASSWORD: changeit
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - default
    ports:
      - 8080:8080
    volumes:
      - ./secrets/client.keystore.jks:/etc/kafka/secrets/client.keystore.jks
      - ./secrets/truststore.jks:/etc/kafka/secrets/truststore.jks
networks:
  default:
    driver: bridge
    name: service-network
