services:
  # ---------------------------------------------------------------------------
  # MinIO Node 1
  # ---------------------------------------------------------------------------
  minio1:
    image: quay.io/minio/minio:latest
    container_name: minio1
    hostname: minio1
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    # [핵심] 4개 노드 전체를 아우르는 주소 지정 -> 분산 모드 자동 활성화
    command: server http://minio{1...4}/data
    ports:
      - "9001:9000" # API: localhost:9001
      - "9011:9001" # Console: localhost:9011
    volumes:
      - minio1_data:/data
    networks:
      - default

  # ---------------------------------------------------------------------------
  # MinIO Node 2
  # ---------------------------------------------------------------------------
  minio2:
    image: quay.io/minio/minio:latest
    container_name: minio2
    hostname: minio2
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server http://minio{1...4}/data
    ports:
      - "9002:9000"
      - "9012:9001"
    volumes:
      - minio2_data:/data
    networks:
      - default

  # ---------------------------------------------------------------------------
  # MinIO Node 3
  # ---------------------------------------------------------------------------
  minio3:
    image: quay.io/minio/minio:latest
    container_name: minio3
    hostname: minio3
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server http://minio{1...4}/data
    ports:
      - "9003:9000"
      - "9013:9001"
    volumes:
      - minio3_data:/data
    networks:
      - default

  # ---------------------------------------------------------------------------
  # MinIO Node 4
  # ---------------------------------------------------------------------------
  minio4:
    image: quay.io/minio/minio:latest
    container_name: minio4
    hostname: minio4
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server http://minio{1...4}/data
    ports:
      - "9004:9000"
      - "9014:9001"
    volumes:
      - minio4_data:/data
    networks:
      - default

  # ---------------------------------------------------------------------------
  # 초기화 작업 (버킷 생성)
  # ---------------------------------------------------------------------------
  minio_mc:
    image: minio/mc
    container_name: minio_mc
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS}
      MINIO_ALIAS: ${MINIO_ALIAS}
    entrypoint:
      - /bin/sh
      - -c
      - |
        # 4개 노드 중 아무 곳(minio1)에나 연결하면 클러스터 전체가 제어됨
        until /usr/bin/mc alias set $${MINIO_ALIAS} http://minio1:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}; do
          echo 'Waiting for MinIO Cluster...'
          sleep 1
        done

        if [ -z "$${MINIO_DEFAULT_BUCKETS}" ]; then
          echo "No buckets to create."
        else
          for BUCKET in $(echo $${MINIO_DEFAULT_BUCKETS} | tr ',' ' '); do
            /usr/bin/mc mb myminio/$$BUCKET --ignore-existing
            echo "Bucket '$$BUCKET' created on Cluster."
          done
        fi

        echo 'MinIO Cluster init complete.'
        tail -f /dev/null
    networks:
      - default

networks:
  default:
    driver: bridge
    name: service-network

volumes:
  minio1_data:
  minio2_data:
  minio3_data:
  minio4_data:
